apiVersion : apps/v1
kind: Deployment
metadata:
  name: abramchuk-lamp-deploy
  labels:
    app :  abramchuk-lamp-deploy
spec:
#  replicas: 2
  selector:
    matchLabels:
      project: lamp
  template:
    metadata:
      labels:
        project: lamp
    spec:
      containers:
      - name : web
        image: andriiabramchuk/php-apache:8.1.1
        ports:
        - containerPort: 80
      - name : database
        image: andriiabramchuk/mariadb:latest
        ports:
        - containerPort: 3306
