apiVersion: v1
kind: Service
metadata:
  name: abramchuk-lamp-service
  labels:
    env  : prod
    owner: andriiabramchuk
spec:
  selector:
    project: lamp
  ports:
    - name      : lamp
      protocol  : TCP
      port      : 80
      targetPort: 80
  type: LoadBalancer
